branches:
  only:
  - master
language: node_js
node_js:
- '8'
before_install:
- npm install
script:
- npm run build
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: public
  on:
    branch: master
- provider: npm
  email: marc@marcnuri.com
  api_key: "$NPMJS_TOKEN"
env:
  global:
  - secure: h/PDx2Bk5RCOCaov8ATINJk4LN4lOV3yydHgxraCPeSYeQrIEskc/v3xXxHCj8qsh7rQ3NkrclvOiCTaOMqAlJXxQYGfkdSNhGOgd7+jQn6UWtzYz5wBT98iD0jUftojDkvaXAkrDSCx2d+Ti7mCqwSg1Bx59LRrQZUVFNL+yQ7MywqCiX5Ic7WwvybNdQwaBZKbPFheN1E6+LSRZxeUJ70+UrX5GGI7rdk7BwitWfhtvhIUaDW3atEYzTtq8tN3oWu6Q/n2W4CxvZezf6DGQWtcS70rxEG5OZbEhj0IrPkk6Tg/qrVQnEGKxvczkH2fHl9IgVURamzwsIsSi4wd9Nvo7piZlm1J0CzzGvHu+TRb9trnx+eNuHmH7vyhQvWGOAs5JRKPyP6LQfkUlxl/8XbeUYLt3htgf9cl92dsfNUCKHEG4pC4An/XMD6FVxVontrNdJwORIeb37licywllBJMJ3lgLvGkKQLQJPL0eYgYFan08jgHW+U+nN8MhYx+IZPkypAFQxi/pNuqVa+TH02g5nx81/1/S3xwohz4qffLU3bn9vzF2tQTeg4hyndOvuePKlX3IgNdvu8VHd876Q2Eyrgn+ecZBkCYfDIVI5+2TNAI6neEBx8+XsSyg3UyU0UjLP3aSV6Kmvmkut4l0NRvQaR+QlqPccuH9DNeOAs=
  - secure: J0i3H7Bcdge9COxcSwYodjFk7j0GfbJSOh4LzvgJ1IJnXcEKE1P0Jov4v9JKDmzOWkwEG2IbOaxqHO8goSJVU6Ar6TSBtI6Vn9m3H9no+kwhQ3vX+ggKatCBocFQuElG6VViSeUquzGBzsjFJHmOhs6lm79YRZI+2/a8dg47PRsRps0uxd47D9Z7jkDOtcxPOBt3AfyTOmvSmHxfv7W19sGSjWuMH0xzuX6w5oJoqx/1K6Z0a/3Q34NqeeDPmmHWlYnNPaeBrq/CIR3UQdPW1hm5FDHZ9rPWpPJZGssdwt5qQzItO/VfuikohCZGxY0A4Q0HET4CjBryEBOY3igr09pd9NkbFSccwNzT3ZetetWABRaAXwB+ppaNFBPj/XOwvZDrEETb63BmdtLTlcA3NrfetKXW4u2oXtUinGWyWIvcqqFAL7yLD3xVjRZa1JyPwEApjQg0Y+8Zh43anj0a/lMH1ZxINyxX1tBldps3KobBoITR//gvqkGfOnMaDWCnAD0DT0liwETQRygJqh5fGM7t/zrqs9mNrqvW3elk5tEgDhe0p0+0baKYaHsSpJzsSQtBcWIUCRKrwARVqDke0/3+suoqqEumWEMmR1YWpCxahDGr27iPd0vSdt4SmPFfjW1RQb9U3gfbYisyaqvOyntk6LendjVPraEANwN85G8=
